/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_tb2;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import org.jfree.chart.ChartFactory;
//import org.jfree.chart.ChartFrame;
//import org.jfree.chart.JFreeChart;
//import org.jfree.chart.plot.PiePlot;
//import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Administradores = new javax.swing.JDialog();
        bt_CRUD_Software = new javax.swing.JButton();
        bt_CRUD_Desarollador = new javax.swing.JButton();
        bt_Salir_Admins = new javax.swing.JButton();
        bt_Grafica_Circular = new javax.swing.JButton();
        jd_CRUD_Software = new javax.swing.JDialog();
        jtf_Codigo_Proyecto = new javax.swing.JTextField();
        jtf_Nombre_Proyecto = new javax.swing.JTextField();
        jtf_FechaI_Proyecto = new javax.swing.JTextField();
        jtf_FechaF_Proyecto = new javax.swing.JTextField();
        jl_Codigo_Proyecto = new javax.swing.JLabel();
        jl_Nombre_Proyecto = new javax.swing.JLabel();
        jl_Fecha_Inicio = new javax.swing.JLabel();
        jl_FechaF_Proyecto = new javax.swing.JLabel();
        bt_Crear_Proyecto = new javax.swing.JButton();
        bt_Ver_Proyectos = new javax.swing.JButton();
        bt_Cerrar_Proyectos = new javax.swing.JButton();
        jtf_equipoDes_proyecto = new javax.swing.JTextField();
        jtf_listaBugs_proyecto = new javax.swing.JTextField();
        jtf_listaBugsFin_proyecto = new javax.swing.JTextField();
        jl_Equipo_Desarollador = new javax.swing.JLabel();
        jl_Lista_Bugs = new javax.swing.JLabel();
        jl_Lista_Bugs_Finalizados = new javax.swing.JLabel();
        jd_CRUD_Desarollador = new javax.swing.JDialog();
        bt_Crear_Desarollador = new javax.swing.JButton();
        bt_Cerrar_CRUD_Desarollador = new javax.swing.JButton();
        bt_Ver_Desarolladores = new javax.swing.JButton();
        jtf_Codigo_Desarollador = new javax.swing.JTextField();
        jtf_Lenguaje_Domina = new javax.swing.JTextField();
        jtf_Nombre_Empleado = new javax.swing.JTextField();
        jtf_Tecnologia_Domina = new javax.swing.JTextField();
        jl_Codigo_Desarollador = new javax.swing.JLabel();
        jl_Nombre_Desarollador = new javax.swing.JLabel();
        jl_Lengauaje_Domina = new javax.swing.JLabel();
        jl_Tecnologia_Domina = new javax.swing.JLabel();
        jd_Ver_Desarollador = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Desarolladores = new javax.swing.JTable();
        bt_Modificar_Desarollador = new javax.swing.JButton();
        bt_Cerrar_Ver_Desarrollador = new javax.swing.JButton();
        bt_Borrar_Desarollador = new javax.swing.JButton();
        BugFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        text5 = new javax.swing.JTextField();
        text4 = new javax.swing.JTextField();
        text3 = new javax.swing.JTextField();
        text2 = new javax.swing.JTextField();
        text1 = new javax.swing.JTextField();
        text6 = new javax.swing.JTextField();
        text7 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        B_BugInsertar = new javax.swing.JButton();
        jd_Ver_Projectos = new javax.swing.JDialog();
        bt_Modificar_Proyecto = new javax.swing.JButton();
        bt_Cerrar_Ver_Software = new javax.swing.JButton();
        bt_Borrar_Proyecto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_Projectos_Software = new javax.swing.JTable();
        jd_QA = new javax.swing.JDialog();
        bt_Bug_QA = new javax.swing.JButton();
        jd_Desarollador = new javax.swing.JDialog();
        bt_Ver_Proyectos_Desarollador = new javax.swing.JButton();
        bt_Bugs_Finalizados = new javax.swing.JButton();
        bt_Asignar_Fecha_Bug = new javax.swing.JButton();
        jtf_Roll = new javax.swing.JTextField();
        bt_Login = new javax.swing.JButton();
        jpf_Contraseña = new javax.swing.JPasswordField();
        jl_Rol = new javax.swing.JLabel();
        jl_Contraseña = new javax.swing.JLabel();
        jl_Usuario = new javax.swing.JLabel();
        jtf_Usuario = new javax.swing.JTextField();
        jbt_Crear_Usuario = new javax.swing.JButton();

        bt_CRUD_Software.setText("CRUD Sofware");
        bt_CRUD_Software.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_CRUD_SoftwareMouseClicked(evt);
            }
        });

        bt_CRUD_Desarollador.setText("CRUD Desarollador");
        bt_CRUD_Desarollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_CRUD_DesarolladorMouseClicked(evt);
            }
        });

        bt_Salir_Admins.setText("Salir");
        bt_Salir_Admins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Salir_AdminsMouseClicked(evt);
            }
        });

        bt_Grafica_Circular.setText("Grafica Cricular");
        bt_Grafica_Circular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Grafica_CircularMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_AdministradoresLayout = new javax.swing.GroupLayout(jd_Administradores.getContentPane());
        jd_Administradores.getContentPane().setLayout(jd_AdministradoresLayout);
        jd_AdministradoresLayout.setHorizontalGroup(
            jd_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AdministradoresLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jd_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_Grafica_Circular)
                    .addGroup(jd_AdministradoresLayout.createSequentialGroup()
                        .addComponent(bt_CRUD_Software)
                        .addGap(18, 18, 18)
                        .addComponent(bt_CRUD_Desarollador)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Salir_Admins)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_AdministradoresLayout.setVerticalGroup(
            jd_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AdministradoresLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(bt_Grafica_Circular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(jd_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_CRUD_Software)
                    .addComponent(bt_CRUD_Desarollador)
                    .addComponent(bt_Salir_Admins))
                .addGap(43, 43, 43))
        );

        jl_Codigo_Proyecto.setText("Codigo del Proyecto");

        jl_Nombre_Proyecto.setText("Nombre del Proyecto");

        jl_Fecha_Inicio.setText("Fecha de Inicio");

        jl_FechaF_Proyecto.setText("Fecha de Finalizacion");

        bt_Crear_Proyecto.setText("Crear");
        bt_Crear_Proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Crear_ProyectoActionPerformed(evt);
            }
        });

        bt_Ver_Proyectos.setText("Ver Proyectos");
        bt_Ver_Proyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Ver_ProyectosMouseClicked(evt);
            }
        });

        bt_Cerrar_Proyectos.setText("Cerrar Ventana");
        bt_Cerrar_Proyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Cerrar_ProyectosMouseClicked(evt);
            }
        });

        jl_Equipo_Desarollador.setText("Equipo Desarrollo");

        jl_Lista_Bugs.setText("Lista de Bugs");

        jl_Lista_Bugs_Finalizados.setText("Lista de Bugs Fin");

        javax.swing.GroupLayout jd_CRUD_SoftwareLayout = new javax.swing.GroupLayout(jd_CRUD_Software.getContentPane());
        jd_CRUD_Software.getContentPane().setLayout(jd_CRUD_SoftwareLayout);
        jd_CRUD_SoftwareLayout.setHorizontalGroup(
            jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                                .addComponent(jl_Codigo_Proyecto)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_Codigo_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_Nombre_Proyecto)
                                    .addComponent(jl_Fecha_Inicio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_Nombre_Proyecto)
                                    .addComponent(jtf_FechaI_Proyecto)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_FechaF_Proyecto)
                                    .addComponent(jl_Equipo_Desarollador)
                                    .addComponent(jl_Lista_Bugs)
                                    .addComponent(jl_Lista_Bugs_Finalizados))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_listaBugs_proyecto)
                                    .addComponent(jtf_equipoDes_proyecto)
                                    .addComponent(jtf_FechaF_Proyecto)
                                    .addComponent(jtf_listaBugsFin_proyecto)))))
                    .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(bt_Crear_Proyecto)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Ver_Proyectos)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Cerrar_Proyectos)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jd_CRUD_SoftwareLayout.setVerticalGroup(
            jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Codigo_Proyecto)
                    .addComponent(jtf_Codigo_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre_Proyecto)
                    .addComponent(jtf_Nombre_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_FechaI_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Fecha_Inicio))
                .addGap(18, 18, 18)
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_FechaF_Proyecto)
                    .addComponent(jtf_FechaF_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_equipoDes_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Equipo_Desarollador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_listaBugs_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Lista_Bugs))
                .addGap(20, 20, 20)
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_listaBugsFin_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Lista_Bugs_Finalizados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Crear_Proyecto)
                    .addComponent(bt_Ver_Proyectos)
                    .addComponent(bt_Cerrar_Proyectos))
                .addGap(30, 30, 30))
        );

        bt_Crear_Desarollador.setText("Crear");
        bt_Crear_Desarollador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Crear_DesarolladorActionPerformed(evt);
            }
        });

        bt_Cerrar_CRUD_Desarollador.setText("Cerrar Ventana");
        bt_Cerrar_CRUD_Desarollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Cerrar_CRUD_DesarolladorMouseClicked(evt);
            }
        });

        bt_Ver_Desarolladores.setText("Ver Desarolladores");
        bt_Ver_Desarolladores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Ver_DesarolladoresMouseClicked(evt);
            }
        });

        jl_Codigo_Desarollador.setText("Codigo de Desarollador");

        jl_Nombre_Desarollador.setText("Nombre");

        jl_Lengauaje_Domina.setText("Lenguaje que domina");

        jl_Tecnologia_Domina.setText("Tecnologia que domina");

        javax.swing.GroupLayout jd_CRUD_DesarolladorLayout = new javax.swing.GroupLayout(jd_CRUD_Desarollador.getContentPane());
        jd_CRUD_Desarollador.getContentPane().setLayout(jd_CRUD_DesarolladorLayout);
        jd_CRUD_DesarolladorLayout.setHorizontalGroup(
            jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CRUD_DesarolladorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_CRUD_DesarolladorLayout.createSequentialGroup()
                        .addComponent(jl_Tecnologia_Domina)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_Tecnologia_Domina))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CRUD_DesarolladorLayout.createSequentialGroup()
                        .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Codigo_Desarollador)
                            .addComponent(jl_Nombre_Desarollador)
                            .addComponent(jl_Lengauaje_Domina)
                            .addComponent(bt_Crear_Desarollador, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_Codigo_Desarollador)
                            .addComponent(jtf_Nombre_Empleado)
                            .addGroup(jd_CRUD_DesarolladorLayout.createSequentialGroup()
                                .addComponent(bt_Ver_Desarolladores)
                                .addGap(18, 18, 18)
                                .addComponent(bt_Cerrar_CRUD_Desarollador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                            .addComponent(jtf_Lenguaje_Domina))))
                .addGap(100, 100, 100))
        );
        jd_CRUD_DesarolladorLayout.setVerticalGroup(
            jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CRUD_DesarolladorLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Codigo_Desarollador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Codigo_Desarollador))
                .addGap(18, 18, 18)
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre_Desarollador)
                    .addComponent(jtf_Nombre_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Lengauaje_Domina)
                    .addComponent(jtf_Lenguaje_Domina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Tecnologia_Domina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Tecnologia_Domina))
                .addGap(75, 75, 75)
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Crear_Desarollador)
                    .addComponent(bt_Ver_Desarolladores)
                    .addComponent(bt_Cerrar_CRUD_Desarollador))
                .addGap(22, 22, 22))
        );

        jt_Desarolladores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Codigo", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_Desarolladores);
        if (jt_Desarolladores.getColumnModel().getColumnCount() > 0) {
            jt_Desarolladores.getColumnModel().getColumn(0).setResizable(false);
            jt_Desarolladores.getColumnModel().getColumn(1).setResizable(false);
        }

        bt_Modificar_Desarollador.setText("Modificar");
        bt_Modificar_Desarollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Modificar_DesarolladorMouseClicked(evt);
            }
        });

        bt_Cerrar_Ver_Desarrollador.setText("Cerrar Ventana");
        bt_Cerrar_Ver_Desarrollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Cerrar_Ver_DesarrolladorMouseClicked(evt);
            }
        });

        bt_Borrar_Desarollador.setText("Borrar");
        bt_Borrar_Desarollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Borrar_DesarolladorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_Ver_DesarolladorLayout = new javax.swing.GroupLayout(jd_Ver_Desarollador.getContentPane());
        jd_Ver_Desarollador.getContentPane().setLayout(jd_Ver_DesarolladorLayout);
        jd_Ver_DesarolladorLayout.setHorizontalGroup(
            jd_Ver_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Ver_DesarolladorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jd_Ver_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_Borrar_Desarollador)
                    .addComponent(bt_Modificar_Desarollador)
                    .addComponent(bt_Cerrar_Ver_Desarrollador))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jd_Ver_DesarolladorLayout.setVerticalGroup(
            jd_Ver_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Ver_DesarolladorLayout.createSequentialGroup()
                .addGroup(jd_Ver_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_Ver_DesarolladorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_Ver_DesarolladorLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(bt_Modificar_Desarollador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Borrar_Desarollador)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Cerrar_Ver_Desarrollador)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Codigo:");

        jLabel10.setText("Descripcion:");

        jLabel12.setText("Codigo de proyecto de software:");

        jLabel14.setText("Nivel de Urgencia[1-5]:");

        jLabel16.setText("Estado: nuevo, asignado o finalizado");

        jLabel17.setText("Fecha inicio de reparacion:");

        jLabel18.setText("Fecha finalizado");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("BUG");

        B_BugInsertar.setText("Insertar");
        B_BugInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BugInsertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BugFrameLayout = new javax.swing.GroupLayout(BugFrame.getContentPane());
        BugFrame.getContentPane().setLayout(BugFrameLayout);
        BugFrameLayout.setHorizontalGroup(
            BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BugFrameLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text5)
                    .addComponent(text4)
                    .addComponent(text3)
                    .addComponent(text2)
                    .addComponent(text1)
                    .addComponent(text6)
                    .addComponent(text7, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BugFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BugFrameLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BugFrameLayout.createSequentialGroup()
                        .addComponent(B_BugInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))))
        );
        BugFrameLayout.setVerticalGroup(
            BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BugFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(66, 66, 66)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(text5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(text6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(text7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(B_BugInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        bt_Modificar_Proyecto.setText("Modificar");
        bt_Modificar_Proyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Modificar_ProyectoMouseClicked(evt);
            }
        });

        bt_Cerrar_Ver_Software.setText("Cerrar Ventana");

        bt_Borrar_Proyecto.setText("Borrar");
        bt_Borrar_Proyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Borrar_ProyectoMouseClicked(evt);
            }
        });

        jt_Projectos_Software.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Proyecto", "Nombre Projecto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_Projectos_Software);
        if (jt_Projectos_Software.getColumnModel().getColumnCount() > 0) {
            jt_Projectos_Software.getColumnModel().getColumn(0).setResizable(false);
            jt_Projectos_Software.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jd_Ver_ProjectosLayout = new javax.swing.GroupLayout(jd_Ver_Projectos.getContentPane());
        jd_Ver_Projectos.getContentPane().setLayout(jd_Ver_ProjectosLayout);
        jd_Ver_ProjectosLayout.setHorizontalGroup(
            jd_Ver_ProjectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Ver_ProjectosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_Ver_ProjectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_Modificar_Proyecto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_Borrar_Proyecto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_Cerrar_Ver_Software, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jd_Ver_ProjectosLayout.setVerticalGroup(
            jd_Ver_ProjectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Ver_ProjectosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_Ver_ProjectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_Ver_ProjectosLayout.createSequentialGroup()
                        .addComponent(bt_Modificar_Proyecto)
                        .addGap(30, 30, 30)
                        .addComponent(bt_Borrar_Proyecto)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Cerrar_Ver_Software)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_Bug_QA.setText("Bug");
        bt_Bug_QA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Bug_QAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_QALayout = new javax.swing.GroupLayout(jd_QA.getContentPane());
        jd_QA.getContentPane().setLayout(jd_QALayout);
        jd_QALayout.setHorizontalGroup(
            jd_QALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jd_QALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_QALayout.createSequentialGroup()
                    .addGap(173, 173, 173)
                    .addComponent(bt_Bug_QA)
                    .addContainerGap(174, Short.MAX_VALUE)))
        );
        jd_QALayout.setVerticalGroup(
            jd_QALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jd_QALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_QALayout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(bt_Bug_QA)
                    .addContainerGap(138, Short.MAX_VALUE)))
        );

        bt_Ver_Proyectos_Desarollador.setText("Ver Proyectos");
        bt_Ver_Proyectos_Desarollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Ver_Proyectos_DesarolladorMouseClicked(evt);
            }
        });

        bt_Bugs_Finalizados.setText("Bugs Finalizados");
        bt_Bugs_Finalizados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Bugs_FinalizadosMouseClicked(evt);
            }
        });

        bt_Asignar_Fecha_Bug.setText("Fecha de Reparacion del bug");
        bt_Asignar_Fecha_Bug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Asignar_Fecha_BugMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_DesarolladorLayout = new javax.swing.GroupLayout(jd_Desarollador.getContentPane());
        jd_Desarollador.getContentPane().setLayout(jd_DesarolladorLayout);
        jd_DesarolladorLayout.setHorizontalGroup(
            jd_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_DesarolladorLayout.createSequentialGroup()
                .addGroup(jd_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_Asignar_Fecha_Bug)
                    .addGroup(jd_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_DesarolladorLayout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(bt_Ver_Proyectos_Desarollador))
                        .addGroup(jd_DesarolladorLayout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(bt_Bugs_Finalizados))))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jd_DesarolladorLayout.setVerticalGroup(
            jd_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_DesarolladorLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(bt_Ver_Proyectos_Desarollador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_Asignar_Fecha_Bug)
                .addGap(8, 8, 8)
                .addComponent(bt_Bugs_Finalizados)
                .addGap(62, 62, 62))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_Login.setText("Login");
        bt_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_LoginMouseClicked(evt);
            }
        });

        jl_Rol.setText("Ingrese su rol");

        jl_Contraseña.setText("Ingrese su contraseña");

        jl_Usuario.setText("Ingrese su correo");

        jbt_Crear_Usuario.setText("Crear Usuario");
        jbt_Crear_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_Crear_UsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Contraseña)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Usuario)
                            .addComponent(jl_Rol)))
                    .addComponent(jbt_Crear_Usuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(bt_Login)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jtf_Roll)
                    .addComponent(jpf_Contraseña, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_Usuario))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_Roll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Rol))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Usuario)
                    .addComponent(jtf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpf_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Contraseña))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Login)
                    .addComponent(jbt_Crear_Usuario))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_LoginMouseClicked
        // TODO add your handling code here:
        String rol;
        String clave;
        String usuario;
        rol = jtf_Roll.getText();
        clave = jpf_Contraseña.getText();
        usuario = jtf_Usuario.getText();
        for (int i = 0; i < users.size(); i++) {
            if (usuario.equalsIgnoreCase(users.get(i).getCorreo()) && clave.equals(users.get(i).getContraseña()) && rol.equalsIgnoreCase("administrador")) {
                jtf_Roll.setText("");
                jpf_Contraseña.setText("");
                jtf_Usuario.setText("");
                jd_Administradores.setLocationRelativeTo(this);
                jd_Administradores.setVisible(true);
                jd_Administradores.setTitle("Ventana Principal de desarolladores");
                jd_Administradores.pack();

            } else if (usuario.equalsIgnoreCase(users.get(i).getCorreo()) && clave.equals(users.get(i).getContraseña()) && rol.equalsIgnoreCase("desarollador")) {
                control = usuario;
                jtf_Roll.setText("");
                jpf_Contraseña.setText("");
                jtf_Usuario.setText("");
                jd_Desarollador.setLocationRelativeTo(this);
                jd_Desarollador.setVisible(true);
                jd_Desarollador.setTitle("Ventana Principal de desarollador");
                jd_Desarollador.pack();
            } else if (usuario.equalsIgnoreCase(users.get(i).getCorreo()) && clave.equals(users.get(i).getContraseña()) && rol.equalsIgnoreCase("qa")) {
                jtf_Roll.setText("");
                jpf_Contraseña.setText("");
                jtf_Usuario.setText("");
                jd_QA.setLocationRelativeTo(this);
                jd_QA.setVisible(true);
                jd_QA.setTitle("Ventana Principal de QA");
                jd_QA.pack();
            }
        }//Fim del for que hace las validaciones del usuario
    }//GEN-LAST:event_bt_LoginMouseClicked

    private void bt_CRUD_SoftwareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CRUD_SoftwareMouseClicked
        // TODO add your handling code here:
        jd_CRUD_Software.setLocationRelativeTo(this);
        jd_CRUD_Software.setVisible(true);
        jd_CRUD_Software.setTitle("CRUD de Software");
        jd_CRUD_Software.pack();
    }//GEN-LAST:event_bt_CRUD_SoftwareMouseClicked

    private void bt_Cerrar_CRUD_DesarolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Cerrar_CRUD_DesarolladorMouseClicked
        // TODO add your handling code here:
        jd_CRUD_Desarollador.setVisible(false);
    }//GEN-LAST:event_bt_Cerrar_CRUD_DesarolladorMouseClicked

    private void bt_CRUD_DesarolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CRUD_DesarolladorMouseClicked
        // TODO add your handling code here:
        jd_CRUD_Desarollador.setLocationRelativeTo(this);
        jd_CRUD_Desarollador.setVisible(true);
        jd_CRUD_Desarollador.setTitle("CRUD de Desarollador");
        jd_CRUD_Desarollador.pack();
    }//GEN-LAST:event_bt_CRUD_DesarolladorMouseClicked

    private void bt_Salir_AdminsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Salir_AdminsMouseClicked
        // TODO add your handling code here:
        jd_Administradores.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_bt_Salir_AdminsMouseClicked

    private void bt_Ver_DesarolladoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Ver_DesarolladoresMouseClicked
        // TODO add your handling code here:
        jd_Ver_Desarollador.setLocationRelativeTo(this);
        jd_Ver_Desarollador.setVisible(true);
        jd_Ver_Desarollador.pack();
        jd_Ver_Desarollador.setTitle("Ver Desarolladores");
        try {

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Codigo");
            model.addColumn("Nombre");
            String sql = "SELECT CODIGO_DESARR,NOMBRE_EMPLEADO FROM EQUIPO_DESARR";

            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");
            st = con.createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{"" + rs.getString("CODIGO_DESARR"), "" + rs.getString("NOMBRE_EMPLEADO")});
            }
            JOptionPane.showMessageDialog(null, "success");

            jt_Desarolladores.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }


    }//GEN-LAST:event_bt_Ver_DesarolladoresMouseClicked

    private void bt_Cerrar_Ver_DesarrolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Cerrar_Ver_DesarrolladorMouseClicked
        // TODO add your handling code here:
        jd_Ver_Desarollador.setVisible(false);
    }//GEN-LAST:event_bt_Cerrar_Ver_DesarrolladorMouseClicked

    private void bt_Borrar_DesarolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Borrar_DesarolladorMouseClicked
        // TODO add your handling code here:
        desarolladores.remove(jt_Desarolladores.getSelectedRow());
        DefaultTableModel model = (DefaultTableModel) jt_Desarolladores.getModel();
        model.removeRow(jt_Desarolladores.getSelectedRow());
        jt_Desarolladores.setModel(model);
        try {
            String sql = "DELETE FROM EQUIPO_DESARR WHERE CODIGO_DESARR=" + jt_Desarolladores.getValueAt(jt_Desarolladores.getSelectedRow(), 0).toString();

            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");

            pst = con.prepareStatement(sql);
            pst.executeUpdate();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_bt_Borrar_DesarolladorMouseClicked

    private void bt_Modificar_DesarolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Modificar_DesarolladorMouseClicked
        // TODO add your handling code here:
        try {
            String input;
            input = JOptionPane.showInputDialog(jd_Ver_Desarollador, "1. Agregar Tecnologia\n2. Agregar Lenguaje\n Ingrese una opcion: ");
            switch (input) {

                case "1": {
                    String desa;
                    String asignar;
                    desa = JOptionPane.showInputDialog(jd_Ver_Desarollador, "Ingrese el codigo del desarollador a agregar la tecnologia: ");
                    asignar = JOptionPane.showInputDialog(jd_Ver_Desarollador, "Ingrese la tecnologia a agregar: ");
                    String sql = "";
                    for (int i = 0; i < desarolladores.size(); i++) {
                        if (desarolladores.get(i).getCodigo_D() == Integer.parseInt(desa)) {
                            desarolladores.get(i).addTecnologia(asignar);
                            sql = "UPDATE EQUIPO_DESARR SET TECNOLOGIAS_DOMINA='" + desarolladores.get(i).getTecnologias() + "' WHERE CODIGO_DESARR=" + desa;
                        }
                    }
                    con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");

                    pst = con.prepareStatement(sql);

                    pst.executeUpdate();
                    break;
                }
                case "2": {
                    String desa;
                    String asignar;
                    desa = JOptionPane.showInputDialog(jd_Ver_Desarollador, "Ingrese el codigo del desarollador a agregar el lenguaje: ");
                    String sql = "";
                    asignar = JOptionPane.showInputDialog(jd_Ver_Desarollador, "Ingrese el lenguaje a agregar: ");

                    for (int i = 0; i < desarolladores.size(); i++) {
                        if (desarolladores.get(i).getCodigo_D() == Integer.parseInt(desa)) {
                            desarolladores.get(i).addLenguaje(asignar);
                            sql = "UPDATE EQUIPO_DESARR SET LENGUAJES_PROGRA_MANEJA='" + desarolladores.get(i).getLenguajes() + "' WHERE CODIGO_DESARR=" + desa;
                        }
                    }
                    con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");

                    pst = con.prepareStatement(sql);

                    pst.executeUpdate();
                }
                break;
                default:
                    JOptionPane.showMessageDialog(jd_Ver_Desarollador, "Opcion no valida");

            }//casos para las opciones para modificar el desarollador

            JOptionPane.showMessageDialog(null, "success");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_bt_Modificar_DesarolladorMouseClicked

    private void B_BugInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BugInsertarActionPerformed
        try {
            String sql = "INSERT INTO BUG (CODIGO, DESCRIPCION, CODIGO_PROYECTO_SOFTWARE, NIVEL_URGENCIA, ESTADO, FECHAINICIO, FECHAFIN)VALUES (?,?,?,?,?,?,?)";

            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");

            pst = con.prepareStatement(sql);

            pst.setString(1, text1.getText());
            pst.setString(2, text2.getText());
            pst.setString(3, text3.getText());
            pst.setString(4, text4.getText());
            pst.setString(5, text5.getText());
            pst.setString(6, text6.getText());
            pst.setString(7, text7.getText());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "success");

            text1.setText("");
            text2.setText("");
            text3.setText("");
            text4.setText("");
            text5.setText("");
            text6.setText("");
            text7.setText("");
            bugs.add(new Bug(Integer.parseInt(text1.getText()), text2.getText(), Integer.parseInt(text3.getText()), Integer.parseInt(text4.getText()), text5.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_B_BugInsertarActionPerformed

    private void bt_Cerrar_ProyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Cerrar_ProyectosMouseClicked
        // TODO add your handling code here:
        jd_CRUD_Software.setVisible(false);
    }//GEN-LAST:event_bt_Cerrar_ProyectosMouseClicked

    private void bt_Borrar_ProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Borrar_ProyectoMouseClicked
        // TODO add your handling code here:
        softwares.remove(jt_Projectos_Software.getSelectedRow());
        DefaultTableModel model = (DefaultTableModel) jt_Projectos_Software.getModel();
        model.removeRow(jt_Projectos_Software.getSelectedRow());
        jt_Projectos_Software.setModel(model);
        try {
            String sql = "DELETE FROM PROYECTO_SOFTWARE WHERE CODIGO_PROYECTO=" + jt_Projectos_Software.getValueAt(jt_Projectos_Software.getSelectedRow(), 0).toString();
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");
            pst = con.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "success");
            softwares.add(new Proyecto_Software(Integer.parseInt(jtf_Codigo_Proyecto.getText()), jtf_Nombre_Proyecto.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_bt_Borrar_ProyectoMouseClicked

    private void bt_Modificar_ProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Modificar_ProyectoMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO PROYECTO_SOFTWARE (CODIGO_PROYECTO, NOMBRE_PROYECTO, FECHAINICIO, FECHAFIN, EQUIPO_DESARR, LISTA_BUGS, LISTA_BUGS_FINALIZADOS)VALUES (?,?,?,?,?,?,?)";

            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");
            pst = con.prepareStatement(sql);
            pst.executeUpdate();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        try {
            String input;
            input = JOptionPane.showInputDialog(jd_Ver_Projectos, "1. Cambiar Nombre\n2. Fecha Inicio\n3. Fecha Finalizacion\n4. Agregar Desarollador"
                    + "\n5. Agregar Bug\n Ingrese una opcion: ");
            switch (input) {
                case "1": {
                    String sql = "";
                    String desa;
                    desa = JOptionPane.showInputDialog(jd_Ver_Projectos, "Ingrese el codigo del proyecto a cambiar nombre: ");
                    String asignar = JOptionPane.showInputDialog(jd_Ver_Projectos, "Ingrese el nuevo nombre: ");
                    for (int i = 0; i < softwares.size(); i++) {
                        if (softwares.get(i).getCodigo_P() == Integer.parseInt(desa)) {
                            softwares.get(i).setNombre_P(asignar);
                        }
                    }
                    sql = "UPDATE PROYECTO_SOFTWARE SET NOMBRE_PROYECTO='" + asignar + "' WHERE CODIGO_PROYECTO=" + desa;
                    con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");
                    pst = con.prepareStatement(sql);
                    pst.executeUpdate();
                    break;
                }
                case "2": {
                    String sql;
                    String desa;
                    String asignar;
                    desa = JOptionPane.showInputDialog(jd_Ver_Projectos, "Ingrese el codigo del proyecto a cambiar la fecha de Inicio: ");

                    asignar = JOptionPane.showInputDialog(jd_Ver_Projectos, "Ingrese nueva fecha inicio: ");
                    sql = "UPDATE PROYECTO_SOFTWARE SET FECHAINICIO='" + asignar + "' WHERE CODIGO_PROYECTO=" + desa;
                    for (int i = 0; i < softwares.size(); i++) {
                        if (softwares.get(i).getCodigo_P() == Integer.parseInt(desa)) {
                            softwares.get(i).setFecha_I(asignar);
                        }
                    }
                    con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");
                    pst = con.prepareStatement(sql);
                    pst.executeUpdate();
                    break;
                }
                case "3": {
                    String sql;
                    String desa;
                    String asignar;
                    desa = JOptionPane.showInputDialog(jd_Ver_Projectos, "Ingrese el codigo del proyecto a cambiar la fecha de finalizacionn: ");

                    asignar = JOptionPane.showInputDialog(jd_Ver_Projectos, "Ingrese nueva fecha finalizacion: ");
                    sql = "UPDATE PROYECTO_SOFTWARE SET FECHAFIN='" + asignar + "' WHERE CODIGO_PROYECTO=" + desa;
                    for (int i = 0; i < softwares.size(); i++) {
                        if (softwares.get(i).getCodigo_P() == Integer.parseInt(desa)) {
                            softwares.get(i).setFecha_F(asignar);
                        }
                    }
                    con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");
                    pst = con.prepareStatement(sql);
                    pst.executeUpdate();
                }
                break;
                case "4": {
                    String sql = "";
                    String desa;
                    String asignar;
                    desa = JOptionPane.showInputDialog(jd_Ver_Desarollador, "Ingrese el codigo del proyecto a asignar el desarollador: ");
                    String desarollador = "";
                    for (int i = 0; i < desarolladores.size(); i++) {
                        desarollador += "" + desarolladores.get(i).getCodigo_D() + "\n";
                    }
                    asignar = JOptionPane.showInputDialog(jd_Ver_Desarollador, desarollador + "\nIngrese un desarollador a asignar");

                    for (int i = 0; i < softwares.size(); i++) {
                        if (softwares.get(i).getCodigo_P() == Integer.parseInt(desa)) {
                            softwares.get(i).addDesarollador(desarolladores.get(Integer.parseInt(asignar)));
                        }
                    }
                    sql = "UPDATE PROYECTO_SOFTWARE SET EQUIPO_DESARR='" + asignar + "' WHERE CODIGO_PROYECTO=" + desa;
                    con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");
                    pst = con.prepareStatement(sql);
                    pst.executeUpdate();
                    break;
                }
                case "5": {
                    String sql = "";
                    String desa;
                    String asignar;
                    desa = JOptionPane.showInputDialog(jd_Ver_Desarollador, "Ingrese el codigo del proyecto a asignar el desarollador: ");
                    String bug = "";
                    for (int i = 0; i < bugs.size(); i++) {
                        bug += "" + bugs.get(i).getCodigo() + "\n";
                    }
                    asignar = JOptionPane.showInputDialog(jd_Ver_Desarollador, bug + "\nIngrese un bug a asignar");

                    for (int i = 0; i < softwares.size(); i++) {
                        if (softwares.get(i).getCodigo_P() == Integer.parseInt(desa)) {
                            softwares.get(i).addBugs(bugs.get(Integer.parseInt(asignar)));
                            sql = "UPDATE PROYECTO_SOFTWARE SET LISTA_BUGS='" + softwares.get(i).getBugs() + "' WHERE CODIGO_PROYECTO=" + desa;
                        }
                    }
                    con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");
                    pst = con.prepareStatement(sql);
                    pst.executeUpdate();
                    break;
                }
                default:
                    JOptionPane.showMessageDialog(jd_Ver_Projectos, "Opcion no valida");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_bt_Modificar_ProyectoMouseClicked

    private void bt_Grafica_CircularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Grafica_CircularMouseClicked
        // TODO add your handling code here:
        try {
            DefaultPieDataset datos = new DefaultPieDataset();
            int asignados = 0;
            int nuevos = 0;
            int finalizados = 0;

            String sql = "SELECT ESTADO FROM BUG";

            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");
            st = con.createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                if (rs.getString("ESTADO").equalsIgnoreCase("nuevo")) {
                    nuevos++;
                } else if (rs.getString("ESTADO").equalsIgnoreCase("asignado")) {
                    asignados++;
                } else if (rs.getString("ESTADO").equalsIgnoreCase("finañizado")) {
                    finalizados++;
                }
            }
            datos.setValue("Nuevos", nuevos);
            datos.setValue("Asignados", asignados);
            datos.setValue("Finalizados", finalizados);

            JFreeChart chart = ChartFactory.createPieChart("Bugs", datos, true, true, true);
            PiePlot p = (PiePlot) chart.getPlot();
            ChartFrame frame = new ChartFrame("Grafico Circular de bugs", chart);
            frame.setVisible(true);
            frame.setSize(450, 500);

            JOptionPane.showMessageDialog(null, "success");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_bt_Grafica_CircularMouseClicked

    private void bt_Bug_QAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Bug_QAMouseClicked
        // TODO add your handling code here:
        BugFrame.pack();
        BugFrame.setLocationRelativeTo(this);
        BugFrame.setVisible(true);
    }//GEN-LAST:event_bt_Bug_QAMouseClicked

    private void bt_Ver_Proyectos_DesarolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Ver_Proyectos_DesarolladorMouseClicked
        // TODO add your handling code here:
        String projects = "";
        for (int i = 0; i < desarolladores.size(); i++) {
            if (desarolladores.get(i).getCodigo_D() == Integer.parseInt(control)) {
                projects += "" + desarolladores.get(i).getProject(i) + "\n";
            }
        }
        JOptionPane.showMessageDialog(jd_Administradores, projects);

    }//GEN-LAST:event_bt_Ver_Proyectos_DesarolladorMouseClicked

    private void bt_Bugs_FinalizadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Bugs_FinalizadosMouseClicked
        // TODO add your handling code here:
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/mm/yyyy HH:mm:ss");
        String comando = "";
        for (int i = 0; i < desarolladores.size(); i++) {
            if (desarolladores.get(i).getCodigo_D() == Integer.parseInt(control) && desarolladores.get(i).getReparar().getEstado().equalsIgnoreCase("asignado")) {
                comando += "" + desarolladores.get(i).getReparar().getCodigo() + "\n";
            }
        }

        String fin = JOptionPane.showInputDialog(jd_Desarollador, comando + "\n Ingrese el codigo del bug a finalizar: ");
        for (int i = 0; i < desarolladores.size(); i++) {
            if (desarolladores.get(i).getCodigo_D() == Integer.parseInt(control) && desarolladores.get(i).getReparar().getCodigo() == (Integer.parseInt(fin))) {
                desarolladores.get(i).getReparar().setEstado("finalizado");
                try {
                    desarolladores.get(i).getReparar().setF_Finalizado((Date) new SimpleDateFormat("dd/mm/yyy").parse(dtf.format(LocalDateTime.now())));
                } catch (ParseException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_bt_Bugs_FinalizadosMouseClicked

    private void bt_Asignar_Fecha_BugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Asignar_Fecha_BugMouseClicked
        // TODO add your handling code here:
        String bug = JOptionPane.showInputDialog(jd_Desarollador, "Ingrese el codigo del bug a asignar fecha: ");
        for (int i = 0; i < desarolladores.size(); i++) {
            if (desarolladores.get(i).getCodigo_D() == Integer.parseInt(control) && desarolladores.get(i).getReparar().getCodigo() == (Integer.parseInt(bug))) {
                try {
                    desarolladores.get(i).getReparar().setF_Inicio((Date) new SimpleDateFormat("dd/mm/yyy").parse(JOptionPane.showInputDialog(jd_Desarollador, "ngrese el codigo del bug a finalizar: ")));
                } catch (ParseException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_bt_Asignar_Fecha_BugMouseClicked

    private void bt_Crear_ProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Crear_ProyectoActionPerformed
        try {
            String sql = "INSERT INTO PROYECTO_SOFTWARE (CODIGO_PROYECTO, NOMBRE_PROYECTO, FECHAINICIO, FECHAFIN, EQUIPO_DESARR, LISTA_BUGS, LISTA_BUGS_FINALIZADOS)VALUES (?,?,?,?,?,?,?)";

            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");

            pst = con.prepareStatement(sql);

            pst.setString(1, jtf_Codigo_Proyecto.getText());
            pst.setString(2, jtf_Nombre_Proyecto.getText());
            pst.setString(3, jtf_FechaI_Proyecto.getText());
            pst.setString(4, jtf_FechaF_Proyecto.getText());
            pst.setString(5, jtf_equipoDes_proyecto.getText());
            pst.setString(6, jtf_listaBugs_proyecto.getText());
            pst.setString(7, jtf_listaBugsFin_proyecto.getText());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "success");

            softwares.add(new Proyecto_Software(Integer.parseInt(jtf_Codigo_Proyecto.getText()), jtf_Nombre_Proyecto.getText()));

            jtf_Codigo_Proyecto.setText("");
            jtf_Nombre_Proyecto.setText("");
            jtf_FechaI_Proyecto.setText("");
            jtf_FechaI_Proyecto.setText("");
            jtf_FechaF_Proyecto.setText("");
            jtf_listaBugs_proyecto.setText("");
            jtf_listaBugsFin_proyecto.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_bt_Crear_ProyectoActionPerformed

    private void bt_Crear_DesarolladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Crear_DesarolladorActionPerformed
        try {
            String sql = "INSERT INTO EQUIPO_DESARR (CODIGO_DESARR, NOMBRE_EMPLEADO, LENGUAJES_PROGRA_MANEJA, TECNOLOGIAS_DOMINA)VALUES (?,?,?,?)";

            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");

            pst = con.prepareStatement(sql);

            pst.setString(1, jtf_Codigo_Desarollador.getText());
            pst.setString(2, jtf_Nombre_Empleado.getText());
            pst.setString(3, jtf_Lenguaje_Domina.getText());
            pst.setString(4, jtf_Tecnologia_Domina.getText());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "success");

            jtf_Codigo_Desarollador.setText("");
            jtf_Nombre_Empleado.setText("");
            jtf_Lenguaje_Domina.setText("");
            jtf_Tecnologia_Domina.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_bt_Crear_DesarolladorActionPerformed

    private void bt_Ver_ProyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Ver_ProyectosMouseClicked
        // TODO add your handling code here:
        jd_Ver_Projectos.setLocationRelativeTo(this);
        jd_Ver_Projectos.setVisible(true);
        jd_Ver_Projectos.setSize(250, 250);

        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Codigo Projecto");
            model.addColumn("Nombre Projecto");
            String sql = "SELECT CODIGO_PROYECTO, NOMBRE_PROYECTO FROM PROYECTO_SOFTWARE";

            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");
            st = con.createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{"" + rs.getString("CODIGO_PROYECTO"), "" + rs.getString("NOMBRE_PROYECTO")});
            }

            JOptionPane.showMessageDialog(null, "success");
            jt_Projectos_Software.setModel(model);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_bt_Ver_ProyectosMouseClicked

    private void jbt_Crear_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_Crear_UsuarioMouseClicked
        // TODO add your handling code here:
        String usario = JOptionPane.showInputDialog(this, "Ingrese el nuevo usuario: ");
        String rol = JOptionPane.showInputDialog(this, "Ingrese el rol: ");
        String contraseña = JOptionPane.showInputDialog(this, "Ingrese la contraseña: ");
        users.add(new Usuario(rol, usario, contraseña));
    }//GEN-LAST:event_jbt_Crear_UsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        agregar_pre();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_BugInsertar;
    private javax.swing.JFrame BugFrame;
    private javax.swing.JButton bt_Asignar_Fecha_Bug;
    private javax.swing.JButton bt_Borrar_Desarollador;
    private javax.swing.JButton bt_Borrar_Proyecto;
    private javax.swing.JButton bt_Bug_QA;
    private javax.swing.JButton bt_Bugs_Finalizados;
    private javax.swing.JButton bt_CRUD_Desarollador;
    private javax.swing.JButton bt_CRUD_Software;
    private javax.swing.JButton bt_Cerrar_CRUD_Desarollador;
    private javax.swing.JButton bt_Cerrar_Proyectos;
    private javax.swing.JButton bt_Cerrar_Ver_Desarrollador;
    private javax.swing.JButton bt_Cerrar_Ver_Software;
    private javax.swing.JButton bt_Crear_Desarollador;
    private javax.swing.JButton bt_Crear_Proyecto;
    private javax.swing.JButton bt_Grafica_Circular;
    private javax.swing.JButton bt_Login;
    private javax.swing.JButton bt_Modificar_Desarollador;
    private javax.swing.JButton bt_Modificar_Proyecto;
    private javax.swing.JButton bt_Salir_Admins;
    private javax.swing.JButton bt_Ver_Desarolladores;
    private javax.swing.JButton bt_Ver_Proyectos;
    private javax.swing.JButton bt_Ver_Proyectos_Desarollador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbt_Crear_Usuario;
    private javax.swing.JDialog jd_Administradores;
    private javax.swing.JDialog jd_CRUD_Desarollador;
    private javax.swing.JDialog jd_CRUD_Software;
    private javax.swing.JDialog jd_Desarollador;
    private javax.swing.JDialog jd_QA;
    private javax.swing.JDialog jd_Ver_Desarollador;
    private javax.swing.JDialog jd_Ver_Projectos;
    private javax.swing.JLabel jl_Codigo_Desarollador;
    private javax.swing.JLabel jl_Codigo_Proyecto;
    private javax.swing.JLabel jl_Contraseña;
    private javax.swing.JLabel jl_Equipo_Desarollador;
    private javax.swing.JLabel jl_FechaF_Proyecto;
    private javax.swing.JLabel jl_Fecha_Inicio;
    private javax.swing.JLabel jl_Lengauaje_Domina;
    private javax.swing.JLabel jl_Lista_Bugs;
    private javax.swing.JLabel jl_Lista_Bugs_Finalizados;
    private javax.swing.JLabel jl_Nombre_Desarollador;
    private javax.swing.JLabel jl_Nombre_Proyecto;
    private javax.swing.JLabel jl_Rol;
    private javax.swing.JLabel jl_Tecnologia_Domina;
    private javax.swing.JLabel jl_Usuario;
    private javax.swing.JPasswordField jpf_Contraseña;
    private javax.swing.JTable jt_Desarolladores;
    private javax.swing.JTable jt_Projectos_Software;
    private javax.swing.JTextField jtf_Codigo_Desarollador;
    private javax.swing.JTextField jtf_Codigo_Proyecto;
    private javax.swing.JTextField jtf_FechaF_Proyecto;
    private javax.swing.JTextField jtf_FechaI_Proyecto;
    private javax.swing.JTextField jtf_Lenguaje_Domina;
    private javax.swing.JTextField jtf_Nombre_Empleado;
    private javax.swing.JTextField jtf_Nombre_Proyecto;
    private javax.swing.JTextField jtf_Roll;
    private javax.swing.JTextField jtf_Tecnologia_Domina;
    private javax.swing.JTextField jtf_Usuario;
    private javax.swing.JTextField jtf_equipoDes_proyecto;
    private javax.swing.JTextField jtf_listaBugsFin_proyecto;
    private javax.swing.JTextField jtf_listaBugs_proyecto;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    private javax.swing.JTextField text5;
    private javax.swing.JTextField text6;
    private javax.swing.JTextField text7;
    // End of variables declaration//GEN-END:variables
    static ArrayList<Usuario> users = new ArrayList();
    String control;
    static ArrayList<Desarollador> desarolladores = new ArrayList();
    static ArrayList<Bug> bugs = new ArrayList();
    static ArrayList<Proyecto_Software> softwares = new ArrayList();

    public static void agregar_pre() {
        users.add(new Usuario("administrador", "administrador@gmail.com", "123"));
        users.add(new Usuario("desarollador", "desarollador@gmail.com", "456"));
        users.add(new Usuario("qa", "qa@gmail.com", "789"));
    }
}
