/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_tb2;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH / 2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Administradores = new javax.swing.JDialog();
        bt_CRUD_Software = new javax.swing.JButton();
        bt_CRUD_Desarollador = new javax.swing.JButton();
        bt_Salir_Admins = new javax.swing.JButton();
        bt_Grafica_Circular = new javax.swing.JButton();
        jd_CRUD_Software = new javax.swing.JDialog();
        jtf_Codigo_Proyecto = new javax.swing.JTextField();
        jtf_Nombre_Proyecto = new javax.swing.JTextField();
        jtf_FechaI_Proyecto = new javax.swing.JTextField();
        jtf_FechaF_Proyecto = new javax.swing.JTextField();
        jl_Codigo_Proyecto = new javax.swing.JLabel();
        jl_Nombre_Proyecto = new javax.swing.JLabel();
        jl_Fecha_Inicio = new javax.swing.JLabel();
        jl_FechaF_Proyecto = new javax.swing.JLabel();
        bt_Crear_Proyecto = new javax.swing.JButton();
        bt_Ver_Proyectos = new javax.swing.JButton();
        bt_Cerrar_Proyectos = new javax.swing.JButton();
        jd_CRUD_Desarollador = new javax.swing.JDialog();
        bt_Crear_Desarollador = new javax.swing.JButton();
        bt_Cerrar_CRUD_Desarollador = new javax.swing.JButton();
        bt_Ver_Desarolladores = new javax.swing.JButton();
        jtf_Codigo_Desarollador = new javax.swing.JTextField();
        jtf_Lenguaje_Domina = new javax.swing.JTextField();
        jtf_Nombre_Empleado = new javax.swing.JTextField();
        jtf_Tecnologia_Domina = new javax.swing.JTextField();
        jl_Codigo_Desarollador = new javax.swing.JLabel();
        jl_Nombre_Desarollador = new javax.swing.JLabel();
        jl_Lengauaje_Domina = new javax.swing.JLabel();
        jl_Tecnologia_Domina = new javax.swing.JLabel();
        jd_Ver_Desarollador = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Desarolladores = new javax.swing.JTable();
        bt_Modificar_Desarollador = new javax.swing.JButton();
        bt_Cerrar_Ver_Desarrollador = new javax.swing.JButton();
        bt_Borrar_Desarollador = new javax.swing.JButton();
        BugFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        text5 = new javax.swing.JTextField();
        text4 = new javax.swing.JTextField();
        text3 = new javax.swing.JTextField();
        text2 = new javax.swing.JTextField();
        text1 = new javax.swing.JTextField();
        text6 = new javax.swing.JTextField();
        text7 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        B_BugInsertar = new javax.swing.JButton();
        jd_Ver_Projectos = new javax.swing.JDialog();
        bt_Modificar_Proyecto = new javax.swing.JButton();
        bt_Cerrar_Ver_Software = new javax.swing.JButton();
        bt_Borrar_Proyecto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_Projectos_Software = new javax.swing.JTable();
        jd_QA = new javax.swing.JDialog();
        bt_Bug_QA = new javax.swing.JButton();
        jtf_Roll = new javax.swing.JTextField();
        bt_Login = new javax.swing.JButton();
        jpf_Contraseña = new javax.swing.JPasswordField();
        jl_Rol = new javax.swing.JLabel();
        jl_Contraseña = new javax.swing.JLabel();
        jl_Usuario = new javax.swing.JLabel();
        jtf_Usuario = new javax.swing.JTextField();

        bt_CRUD_Software.setText("CRUD Sofware");
        bt_CRUD_Software.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_CRUD_SoftwareMouseClicked(evt);
            }
        });

        bt_CRUD_Desarollador.setText("CRUD Desarollador");
        bt_CRUD_Desarollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_CRUD_DesarolladorMouseClicked(evt);
            }
        });

        bt_Salir_Admins.setText("Salir");
        bt_Salir_Admins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Salir_AdminsMouseClicked(evt);
            }
        });

        bt_Grafica_Circular.setText("Grafica Cricular");
        bt_Grafica_Circular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Grafica_CircularMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_AdministradoresLayout = new javax.swing.GroupLayout(jd_Administradores.getContentPane());
        jd_Administradores.getContentPane().setLayout(jd_AdministradoresLayout);
        jd_AdministradoresLayout.setHorizontalGroup(
            jd_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AdministradoresLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jd_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_Grafica_Circular)
                    .addGroup(jd_AdministradoresLayout.createSequentialGroup()
                        .addComponent(bt_CRUD_Software)
                        .addGap(18, 18, 18)
                        .addComponent(bt_CRUD_Desarollador)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Salir_Admins)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_AdministradoresLayout.setVerticalGroup(
            jd_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AdministradoresLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(bt_Grafica_Circular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(jd_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_CRUD_Software)
                    .addComponent(bt_CRUD_Desarollador)
                    .addComponent(bt_Salir_Admins))
                .addGap(43, 43, 43))
        );

        jl_Codigo_Proyecto.setText("Codigo del Proyecto");

        jl_Nombre_Proyecto.setText("Nombre del Proyecto");

        jl_Fecha_Inicio.setText("Fecha de Inicio");

        jl_FechaF_Proyecto.setText("Fecha de Finalizacion");

        bt_Crear_Proyecto.setText("Crear");
        bt_Crear_Proyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Crear_ProyectoMouseClicked(evt);
            }
        });

        bt_Ver_Proyectos.setText("Ver Proyectos");

        bt_Cerrar_Proyectos.setText("Cerrar Ventana");
        bt_Cerrar_Proyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Cerrar_ProyectosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_CRUD_SoftwareLayout = new javax.swing.GroupLayout(jd_CRUD_Software.getContentPane());
        jd_CRUD_Software.getContentPane().setLayout(jd_CRUD_SoftwareLayout);
        jd_CRUD_SoftwareLayout.setHorizontalGroup(
            jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jl_FechaF_Proyecto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtf_FechaF_Proyecto))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jl_Codigo_Proyecto)
                            .addGap(18, 18, 18)
                            .addComponent(jtf_Codigo_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jl_Nombre_Proyecto)
                                .addComponent(jl_Fecha_Inicio))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf_Nombre_Proyecto)
                                .addComponent(jtf_FechaI_Proyecto))))
                    .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(bt_Crear_Proyecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Ver_Proyectos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Cerrar_Proyectos)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jd_CRUD_SoftwareLayout.setVerticalGroup(
            jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Codigo_Proyecto)
                    .addComponent(jtf_Codigo_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre_Proyecto)
                    .addComponent(jtf_Nombre_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_FechaI_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Fecha_Inicio))
                .addGap(18, 18, 18)
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_FechaF_Proyecto)
                    .addComponent(jtf_FechaF_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Crear_Proyecto)
                    .addComponent(bt_Ver_Proyectos)
                    .addComponent(bt_Cerrar_Proyectos))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        bt_Crear_Desarollador.setText("Crear");
        bt_Crear_Desarollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Crear_DesarolladorMouseClicked(evt);
            }
        });

        bt_Cerrar_CRUD_Desarollador.setText("Cerrar Ventana");
        bt_Cerrar_CRUD_Desarollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Cerrar_CRUD_DesarolladorMouseClicked(evt);
            }
        });

        bt_Ver_Desarolladores.setText("Ver Desarolladores");
        bt_Ver_Desarolladores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Ver_DesarolladoresMouseClicked(evt);
            }
        });

        jl_Codigo_Desarollador.setText("Codigo de Desarollador");

        jl_Nombre_Desarollador.setText("Nombre");

        jl_Lengauaje_Domina.setText("Lenguaje que domina");

        jl_Tecnologia_Domina.setText("Tecnologia que domina");

        javax.swing.GroupLayout jd_CRUD_DesarolladorLayout = new javax.swing.GroupLayout(jd_CRUD_Desarollador.getContentPane());
        jd_CRUD_Desarollador.getContentPane().setLayout(jd_CRUD_DesarolladorLayout);
        jd_CRUD_DesarolladorLayout.setHorizontalGroup(
            jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CRUD_DesarolladorLayout.createSequentialGroup()
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_CRUD_DesarolladorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl_Tecnologia_Domina)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_Tecnologia_Domina))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CRUD_DesarolladorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_Crear_Desarollador)
                            .addComponent(jl_Codigo_Desarollador)
                            .addComponent(jl_Nombre_Desarollador)
                            .addComponent(jl_Lengauaje_Domina))
                        .addGap(18, 18, 18)
                        .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_Codigo_Desarollador)
                            .addComponent(jtf_Nombre_Empleado)
                            .addGroup(jd_CRUD_DesarolladorLayout.createSequentialGroup()
                                .addComponent(bt_Ver_Desarolladores)
                                .addGap(18, 18, 18)
                                .addComponent(bt_Cerrar_CRUD_Desarollador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                            .addComponent(jtf_Lenguaje_Domina))))
                .addGap(100, 100, 100))
        );
        jd_CRUD_DesarolladorLayout.setVerticalGroup(
            jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CRUD_DesarolladorLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Codigo_Desarollador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Codigo_Desarollador))
                .addGap(18, 18, 18)
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre_Desarollador)
                    .addComponent(jtf_Nombre_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Lengauaje_Domina)
                    .addComponent(jtf_Lenguaje_Domina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Tecnologia_Domina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Tecnologia_Domina))
                .addGap(75, 75, 75)
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Crear_Desarollador)
                    .addComponent(bt_Ver_Desarolladores)
                    .addComponent(bt_Cerrar_CRUD_Desarollador))
                .addGap(22, 22, 22))
        );

        jt_Desarolladores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Codigo", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_Desarolladores);
        if (jt_Desarolladores.getColumnModel().getColumnCount() > 0) {
            jt_Desarolladores.getColumnModel().getColumn(0).setResizable(false);
            jt_Desarolladores.getColumnModel().getColumn(1).setResizable(false);
        }

        bt_Modificar_Desarollador.setText("Modificar");
        bt_Modificar_Desarollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Modificar_DesarolladorMouseClicked(evt);
            }
        });

        bt_Cerrar_Ver_Desarrollador.setText("Cerrar Ventana");
        bt_Cerrar_Ver_Desarrollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Cerrar_Ver_DesarrolladorMouseClicked(evt);
            }
        });

        bt_Borrar_Desarollador.setText("Borrar");
        bt_Borrar_Desarollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Borrar_DesarolladorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_Ver_DesarolladorLayout = new javax.swing.GroupLayout(jd_Ver_Desarollador.getContentPane());
        jd_Ver_Desarollador.getContentPane().setLayout(jd_Ver_DesarolladorLayout);
        jd_Ver_DesarolladorLayout.setHorizontalGroup(
            jd_Ver_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Ver_DesarolladorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jd_Ver_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_Borrar_Desarollador)
                    .addComponent(bt_Modificar_Desarollador)
                    .addComponent(bt_Cerrar_Ver_Desarrollador))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jd_Ver_DesarolladorLayout.setVerticalGroup(
            jd_Ver_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Ver_DesarolladorLayout.createSequentialGroup()
                .addGroup(jd_Ver_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_Ver_DesarolladorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_Ver_DesarolladorLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(bt_Modificar_Desarollador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Borrar_Desarollador)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Cerrar_Ver_Desarrollador)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Codigo:");

        jLabel10.setText("Descripcion:");

        jLabel12.setText("Codigo de proyecto de software:");

        jLabel14.setText("Nivel de Urgencia[1-5]:");

        jLabel16.setText("Estado: nuevo, asignado o finalizado");

        jLabel17.setText("Fecha inicio de reparacion:");

        jLabel18.setText("Fecha finalizado");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("BUG");

        B_BugInsertar.setText("Insertar");
        B_BugInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BugInsertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BugFrameLayout = new javax.swing.GroupLayout(BugFrame.getContentPane());
        BugFrame.getContentPane().setLayout(BugFrameLayout);
        BugFrameLayout.setHorizontalGroup(
            BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BugFrameLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text5)
                    .addComponent(text4)
                    .addComponent(text3)
                    .addComponent(text2)
                    .addComponent(text1)
                    .addComponent(text6)
                    .addComponent(text7, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BugFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BugFrameLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BugFrameLayout.createSequentialGroup()
                        .addComponent(B_BugInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))))
        );
        BugFrameLayout.setVerticalGroup(
            BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BugFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(66, 66, 66)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(text5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(text6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BugFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(text7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(B_BugInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        bt_Modificar_Proyecto.setText("Modificar");
        bt_Modificar_Proyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Modificar_ProyectoMouseClicked(evt);
            }
        });

        bt_Cerrar_Ver_Software.setText("Cerrar Ventana");

        bt_Borrar_Proyecto.setText("Borrar");
        bt_Borrar_Proyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Borrar_ProyectoMouseClicked(evt);
            }
        });

        jt_Projectos_Software.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Proyecto", "Nombre Projecto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_Projectos_Software);
        if (jt_Projectos_Software.getColumnModel().getColumnCount() > 0) {
            jt_Projectos_Software.getColumnModel().getColumn(0).setResizable(false);
            jt_Projectos_Software.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jd_Ver_ProjectosLayout = new javax.swing.GroupLayout(jd_Ver_Projectos.getContentPane());
        jd_Ver_Projectos.getContentPane().setLayout(jd_Ver_ProjectosLayout);
        jd_Ver_ProjectosLayout.setHorizontalGroup(
            jd_Ver_ProjectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Ver_ProjectosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_Ver_ProjectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_Modificar_Proyecto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_Borrar_Proyecto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_Cerrar_Ver_Software, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jd_Ver_ProjectosLayout.setVerticalGroup(
            jd_Ver_ProjectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Ver_ProjectosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_Ver_ProjectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_Ver_ProjectosLayout.createSequentialGroup()
                        .addComponent(bt_Modificar_Proyecto)
                        .addGap(30, 30, 30)
                        .addComponent(bt_Borrar_Proyecto)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Cerrar_Ver_Software)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_Bug_QA.setText("Bug");
        bt_Bug_QA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Bug_QAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_QALayout = new javax.swing.GroupLayout(jd_QA.getContentPane());
        jd_QA.getContentPane().setLayout(jd_QALayout);
        jd_QALayout.setHorizontalGroup(
            jd_QALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jd_QALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_QALayout.createSequentialGroup()
                    .addGap(173, 173, 173)
                    .addComponent(bt_Bug_QA)
                    .addContainerGap(174, Short.MAX_VALUE)))
        );
        jd_QALayout.setVerticalGroup(
            jd_QALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jd_QALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_QALayout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(bt_Bug_QA)
                    .addContainerGap(138, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_Login.setText("Login");
        bt_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_LoginMouseClicked(evt);
            }
        });

        jl_Rol.setText("Ingrese su rol");

        jl_Contraseña.setText("Ingrese su contraseña");

        jl_Usuario.setText("Ingrese su usario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Contraseña)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Usuario)
                            .addComponent(jl_Rol))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(bt_Login)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jtf_Roll)
                    .addComponent(jpf_Contraseña, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_Usuario))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_Roll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Rol))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Usuario)
                    .addComponent(jtf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpf_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Contraseña))
                .addGap(18, 18, 18)
                .addComponent(bt_Login)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_LoginMouseClicked
        // TODO add your handling code here:
        String rol;
        String clave;
        String usuario;
        rol = jtf_Roll.getText();
        clave = jpf_Contraseña.getText();
        usuario = jtf_Usuario.getText();
        for (int i = 0; i < users.size(); i++) {
            if (usuario.equalsIgnoreCase(users.get(i).getCredenciales()) && clave.equals(users.get(i).getClave()) && rol.equalsIgnoreCase("administrador")) {
                jtf_Roll.setText("");
                jpf_Contraseña.setText("");
                jtf_Usuario.setText("");
                jd_Administradores.setLocationRelativeTo(this);
                jd_Administradores.setVisible(true);
                jd_Administradores.setSize(250, 250);
                
            } else if (usuario.equalsIgnoreCase(users.get(i).getCredenciales()) && clave.equals(users.get(i).getClave()) && rol.equalsIgnoreCase("desarollador")) {
                jtf_Roll.setText("");
                jpf_Contraseña.setText("");
                jtf_Usuario.setText("");
                System.out.println("desarollador");
            } else if (usuario.equalsIgnoreCase(users.get(i).getCredenciales()) && clave.equals(users.get(i).getClave()) && rol.equalsIgnoreCase("qa")) {
                jtf_Roll.setText("");
                jpf_Contraseña.setText("");
                jtf_Usuario.setText("");
                jd_QA.setLocationRelativeTo(this);
                jd_QA.setVisible(true);
                jd_QA.setSize(250, 250);
            }
        }//Fim del for que hace las validaciones del usuario
    }//GEN-LAST:event_bt_LoginMouseClicked

    private void bt_CRUD_SoftwareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CRUD_SoftwareMouseClicked
        // TODO add your handling code here:
        jd_CRUD_Software.setLocationRelativeTo(this);
        jd_CRUD_Software.setVisible(true);
        jd_CRUD_Software.setSize(250, 250);
    }//GEN-LAST:event_bt_CRUD_SoftwareMouseClicked

    private void bt_Cerrar_CRUD_DesarolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Cerrar_CRUD_DesarolladorMouseClicked
        // TODO add your handling code here:
        jd_CRUD_Desarollador.setVisible(false);
    }//GEN-LAST:event_bt_Cerrar_CRUD_DesarolladorMouseClicked

    private void bt_Crear_DesarolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Crear_DesarolladorMouseClicked
        // TODO add your handling code here:
        Desarollador de = new Desarollador(Integer.parseInt(jtf_Codigo_Desarollador.getText()), jtf_Nombre_Empleado.getText());
        de.addLenguaje(jtf_Lenguaje_Domina.getText());
        de.addTecnologia(jtf_Tecnologia_Domina.getText());
        users.add(new Usuarios(jtf_Codigo_Desarollador.getText(), "123"));
        desarolladores.add(de);
        jtf_Codigo_Desarollador.setText("");
        jtf_Nombre_Empleado.setText("");
        jtf_Lenguaje_Domina.setText("");
        jtf_Tecnologia_Domina.setText("");
    }//GEN-LAST:event_bt_Crear_DesarolladorMouseClicked

    private void bt_CRUD_DesarolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CRUD_DesarolladorMouseClicked
        // TODO add your handling code here:
        jd_CRUD_Desarollador.setLocationRelativeTo(this);
        jd_CRUD_Desarollador.setVisible(true);
        jd_CRUD_Desarollador.setSize(250, 250);
    }//GEN-LAST:event_bt_CRUD_DesarolladorMouseClicked

    private void bt_Salir_AdminsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Salir_AdminsMouseClicked
        // TODO add your handling code here:
        jd_Administradores.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_bt_Salir_AdminsMouseClicked

    private void bt_Ver_DesarolladoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Ver_DesarolladoresMouseClicked
        // TODO add your handling code here:
        jd_Ver_Desarollador.setLocationRelativeTo(this);
        jd_Ver_Desarollador.setVisible(true);
        jd_Ver_Desarollador.setSize(250, 250);
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Codigo");
        model.addColumn("Nombre");
        for (int i = 0; i < desarolladores.size(); i++) {
            model.addRow(new Object[]{"" + desarolladores.get(i).getCodigo_D(), "" + desarolladores.get(i).getNombre()});
        }
        jt_Desarolladores.setModel(model);
    }//GEN-LAST:event_bt_Ver_DesarolladoresMouseClicked

    private void bt_Cerrar_Ver_DesarrolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Cerrar_Ver_DesarrolladorMouseClicked
        // TODO add your handling code here:
        jd_Ver_Desarollador.setVisible(false);
    }//GEN-LAST:event_bt_Cerrar_Ver_DesarrolladorMouseClicked

    private void bt_Borrar_DesarolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Borrar_DesarolladorMouseClicked
        // TODO add your handling code here:
        desarolladores.remove(jt_Desarolladores.getSelectedRow());
        DefaultTableModel model = (DefaultTableModel) jt_Desarolladores.getModel();
        model.removeRow(jt_Desarolladores.getSelectedRow());
        jt_Desarolladores.setModel(model);
    }//GEN-LAST:event_bt_Borrar_DesarolladorMouseClicked

    private void bt_Modificar_DesarolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Modificar_DesarolladorMouseClicked
        // TODO add your handling code here:
        String input;
        input = JOptionPane.showInputDialog(jd_Ver_Desarollador, "1. Asignar Bug\n2. Agregar Tecnologia\n3. Agregar Lenguaje\n Ingrese una opcion: ");
        switch (input) {
            case "1": {
                String desa;
                String asignar;
                desa = JOptionPane.showInputDialog(jd_Ver_Desarollador, "Ingrese el codigo del desarollador a asignar el bug: ");
                String bug = "";
                for (int i = 0; i < bugs.size(); i++) {
                    bug += "" + bugs.get(i).getCodigo() + "\n";
                }
                asignar = JOptionPane.showInputDialog(jd_Ver_Desarollador, bug + "\nIngrese un bug a asignar");
                
                for (int i = 0; i < desarolladores.size(); i++) {
                    if (desarolladores.get(i).getCodigo_D() == Integer.parseInt(desa)) {
                        desarolladores.get(i).setReparar(bugs.get(Integer.parseInt(asignar)));
                    }
                }
                
                break;
            }
            case "2": {
                String desa;
                String asignar;
                desa = JOptionPane.showInputDialog(jd_Ver_Desarollador, "Ingrese el codigo del desarollador a agregar la tecnologia: ");
                
                asignar = JOptionPane.showInputDialog(jd_Ver_Desarollador, "Ingrese la tecnologia a agregar: ");
                
                for (int i = 0; i < desarolladores.size(); i++) {
                    if (desarolladores.get(i).getCodigo_D() == Integer.parseInt(desa)) {
                        desarolladores.get(i).addTecnologia(asignar);
                    }
                }
                break;
            }
            case "3": {
                String desa;
                String asignar;
                desa = JOptionPane.showInputDialog(jd_Ver_Desarollador, "Ingrese el codigo del desarollador a agregar ellenguaje: ");
                
                asignar = JOptionPane.showInputDialog(jd_Ver_Desarollador, "Ingrese el lenguaje a agregar: ");
                
                for (int i = 0; i < desarolladores.size(); i++) {
                    if (desarolladores.get(i).getCodigo_D() == Integer.parseInt(desa)) {
                        desarolladores.get(i).addLenguaje(asignar);
                    }
                }
            }
            break;
            default:
                JOptionPane.showMessageDialog(jd_Ver_Desarollador, "Opcion no valida");
            
        }//casos para las opciones para modificar el desarollador
    }//GEN-LAST:event_bt_Modificar_DesarolladorMouseClicked

    private void B_BugInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BugInsertarActionPerformed
        try {
            String sql = "INSERT INTO BUG (CODIGO, DESCRIPCION, CODIGO_PROYECTO_SOFTWARE, NIVEL_URGENCIA, ESTADO, FECHAINICIO, FECHAFIN)VALUES (?,?,?,?,?,?,?)";
            
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "rick", "workspace@9034");
            
            pst = con.prepareStatement(sql);
            
            pst.setString(1, text1.getText());
            pst.setString(2, text2.getText());
            pst.setString(3, text3.getText());
            pst.setString(4, text4.getText());
            pst.setString(5, text5.getText());
            pst.setString(6, text6.getText());
            pst.setString(7, text7.getText());
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "success");
            
            text1.setText("");
            text2.setText("");
            text3.setText("");
            text4.setText("");
            text5.setText("");
            text6.setText("");
            text7.setText("");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_B_BugInsertarActionPerformed

    private void bt_Crear_ProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Crear_ProyectoMouseClicked
        // TODO add your handling code here:
        int codigo_P = Integer.parseInt(jtf_Codigo_Proyecto.getText());
        String nombre_P = jtf_Nombre_Proyecto.getText();
        String fecha_I = jtf_FechaI_Proyecto.getText();
        String fecha_F = jtf_FechaF_Proyecto.getText();
        softwares.add(new Proyecto_Software(codigo_P, nombre_P, fecha_I, fecha_F));
        jtf_Codigo_Proyecto.setText("");
        jtf_Nombre_Proyecto.setText("");
        jtf_FechaI_Proyecto.setText("");
        jtf_FechaF_Proyecto.setText("");
    }//GEN-LAST:event_bt_Crear_ProyectoMouseClicked

    private void bt_Cerrar_ProyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Cerrar_ProyectosMouseClicked
        // TODO add your handling code here:
        jd_CRUD_Software.setVisible(false);
    }//GEN-LAST:event_bt_Cerrar_ProyectosMouseClicked

    private void bt_Borrar_ProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Borrar_ProyectoMouseClicked
        // TODO add your handling code here:
        softwares.remove(jt_Projectos_Software.getSelectedRow());
        DefaultTableModel model = (DefaultTableModel) jt_Projectos_Software.getModel();
        model.removeRow(jt_Projectos_Software.getSelectedRow());
        jt_Projectos_Software.setModel(model);
    }//GEN-LAST:event_bt_Borrar_ProyectoMouseClicked

    private void bt_Modificar_ProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Modificar_ProyectoMouseClicked
        // TODO add your handling code here:
        String input;
        input = JOptionPane.showInputDialog(jd_Ver_Projectos, "1. Cambiar Nombre\n2. Fecha Inicio\n3. Fecha Finalizacion\n4. Agregar Desarollador"
                + "\n5. Agregar Bug\n Ingrese una opcion: ");
        switch (input) {
            case "1": {
                String desa;
                desa = JOptionPane.showInputDialog(jd_Ver_Projectos, "Ingrese el codigo del proyecto a cambiar nombre: ");
                String asignar = JOptionPane.showInputDialog(jd_Ver_Projectos, "Ingrese el nuevo nombre: ");
                for (int i = 0; i < softwares.size(); i++) {
                    if (softwares.get(i).getCodigo_P() == Integer.parseInt(desa)) {
                        softwares.get(i).setNombre_P(asignar);
                    }
                }
                
                break;
            }
            case "2": {
                String desa;
                String asignar;
                desa = JOptionPane.showInputDialog(jd_Ver_Projectos, "Ingrese el codigo del proyecto a cambiar la fecha de Inicio: ");
                
                asignar = JOptionPane.showInputDialog(jd_Ver_Projectos, "Ingrese nueva fecha inicio: ");
                
                for (int i = 0; i < softwares.size(); i++) {
                    if (softwares.get(i).getCodigo_P() == Integer.parseInt(desa)) {
                        softwares.get(i).setFecha_I(asignar);
                    }
                }
                break;
            }
            case "3": {
                String desa;
                String asignar;
                desa = JOptionPane.showInputDialog(jd_Ver_Projectos, "Ingrese el codigo del proyecto a cambiar la fecha de finalizacionn: ");
                
                asignar = JOptionPane.showInputDialog(jd_Ver_Projectos, "Ingrese nueva fecha finalizacion: ");
                
                for (int i = 0; i < softwares.size(); i++) {
                    if (softwares.get(i).getCodigo_P() == Integer.parseInt(desa)) {
                        softwares.get(i).setFecha_F(asignar);
                    }
                }
            }
            break;
            case "4": {
                
                String desa;
                String asignar;
                desa = JOptionPane.showInputDialog(jd_Ver_Desarollador, "Ingrese el codigo del proyecto a asignar el desarollador: ");
                String desarollador = "";
                for (int i = 0; i < desarolladores.size(); i++) {
                    desarollador += "" + desarolladores.get(i).getCodigo_D() + "\n";
                }
                asignar = JOptionPane.showInputDialog(jd_Ver_Desarollador, desarollador + "\nIngrese un desarollador a asignar");
                
                for (int i = 0; i < softwares.size(); i++) {
                    if (softwares.get(i).getCodigo_P() == Integer.parseInt(desa)) {
                        softwares.get(i).addDesarollador(desarolladores.get(Integer.parseInt(asignar)));
                    }
                }
                
                break;
            }
            case "5": {
                
                String desa;
                String asignar;
                desa = JOptionPane.showInputDialog(jd_Ver_Desarollador, "Ingrese el codigo del proyecto a asignar el desarollador: ");
                String bug = "";
                for (int i = 0; i < bugs.size(); i++) {
                    bug += "" + bugs.get(i).getCodigo() + "\n";
                }
                asignar = JOptionPane.showInputDialog(jd_Ver_Desarollador, bug + "\nIngrese un bug a asignar");
                
                for (int i = 0; i < softwares.size(); i++) {
                    if (softwares.get(i).getCodigo_P() == Integer.parseInt(desa)) {
                        softwares.get(i).addBugs(bugs.get(Integer.parseInt(asignar)));
                    }
                }
                
                break;
            }
            default:
                JOptionPane.showMessageDialog(jd_Ver_Projectos, "Opcion no valida");
        }
    }//GEN-LAST:event_bt_Modificar_ProyectoMouseClicked

    private void bt_Grafica_CircularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Grafica_CircularMouseClicked
        // TODO add your handling code here:
        DefaultPieDataset datos = new DefaultPieDataset();
        int asignados = 0;
        int nuevos = 0;
        int finalizados = 0;
        for (int i = 0; i < bugs.size(); i++) {
            bugs.get(i).getEstado();
            if (bugs.get(i).getEstado().equalsIgnoreCase("nuevo")) {
                nuevos++;
            } else if (bugs.get(i).getEstado().equalsIgnoreCase("asignado")) {
                asignados++;
            } else if (bugs.get(i).getEstado().equalsIgnoreCase("finalizado")) {
                finalizados++;
            }
        }
        
        datos.setValue("Nuevos", nuevos);
        datos.setValue("Asignados", asignados);
        datos.setValue("Finalizados", finalizados);
        
        JFreeChart chart = ChartFactory.createPieChart("Bugs", datos, true, true, true);
        PiePlot p=(PiePlot)chart.getPlot();
        //p.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame=new ChartFrame("Grafico Circular de bugs",chart);
        frame.setVisible(true);
        frame.setSize(450, 500);
    }//GEN-LAST:event_bt_Grafica_CircularMouseClicked

    private void bt_Bug_QAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Bug_QAMouseClicked
        // TODO add your handling code here:
        BugFrame.pack();
        BugFrame.setLocationRelativeTo(this);
        BugFrame.setVisible(true);
    }//GEN-LAST:event_bt_Bug_QAMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        agregar_pre();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_BugInsertar;
    private javax.swing.JFrame BugFrame;
    private javax.swing.JButton bt_Borrar_Desarollador;
    private javax.swing.JButton bt_Borrar_Proyecto;
    private javax.swing.JButton bt_Bug_QA;
    private javax.swing.JButton bt_CRUD_Desarollador;
    private javax.swing.JButton bt_CRUD_Software;
    private javax.swing.JButton bt_Cerrar_CRUD_Desarollador;
    private javax.swing.JButton bt_Cerrar_Proyectos;
    private javax.swing.JButton bt_Cerrar_Ver_Desarrollador;
    private javax.swing.JButton bt_Cerrar_Ver_Software;
    private javax.swing.JButton bt_Crear_Desarollador;
    private javax.swing.JButton bt_Crear_Proyecto;
    private javax.swing.JButton bt_Grafica_Circular;
    private javax.swing.JButton bt_Login;
    private javax.swing.JButton bt_Modificar_Desarollador;
    private javax.swing.JButton bt_Modificar_Proyecto;
    private javax.swing.JButton bt_Salir_Admins;
    private javax.swing.JButton bt_Ver_Desarolladores;
    private javax.swing.JButton bt_Ver_Proyectos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jd_Administradores;
    private javax.swing.JDialog jd_CRUD_Desarollador;
    private javax.swing.JDialog jd_CRUD_Software;
    private javax.swing.JDialog jd_QA;
    private javax.swing.JDialog jd_Ver_Desarollador;
    private javax.swing.JDialog jd_Ver_Projectos;
    private javax.swing.JLabel jl_Codigo_Desarollador;
    private javax.swing.JLabel jl_Codigo_Proyecto;
    private javax.swing.JLabel jl_Contraseña;
    private javax.swing.JLabel jl_FechaF_Proyecto;
    private javax.swing.JLabel jl_Fecha_Inicio;
    private javax.swing.JLabel jl_Lengauaje_Domina;
    private javax.swing.JLabel jl_Nombre_Desarollador;
    private javax.swing.JLabel jl_Nombre_Proyecto;
    private javax.swing.JLabel jl_Rol;
    private javax.swing.JLabel jl_Tecnologia_Domina;
    private javax.swing.JLabel jl_Usuario;
    private javax.swing.JPasswordField jpf_Contraseña;
    private javax.swing.JTable jt_Desarolladores;
    private javax.swing.JTable jt_Projectos_Software;
    private javax.swing.JTextField jtf_Codigo_Desarollador;
    private javax.swing.JTextField jtf_Codigo_Proyecto;
    private javax.swing.JTextField jtf_FechaF_Proyecto;
    private javax.swing.JTextField jtf_FechaI_Proyecto;
    private javax.swing.JTextField jtf_Lenguaje_Domina;
    private javax.swing.JTextField jtf_Nombre_Empleado;
    private javax.swing.JTextField jtf_Nombre_Proyecto;
    private javax.swing.JTextField jtf_Roll;
    private javax.swing.JTextField jtf_Tecnologia_Domina;
    private javax.swing.JTextField jtf_Usuario;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    private javax.swing.JTextField text5;
    private javax.swing.JTextField text6;
    private javax.swing.JTextField text7;
    // End of variables declaration//GEN-END:variables
    static ArrayList<Usuarios> users = new ArrayList();
    static ArrayList<Desarollador> desarolladores = new ArrayList();
    static ArrayList<Bug> bugs = new ArrayList();
    static ArrayList<Proyecto_Software> softwares = new ArrayList();
    
    public static void agregar_pre() {
        users.add(new Usuarios("administrador", "123"));
        users.add(new Usuarios("desarollador", "456"));
        users.add(new Usuarios("qa", "789"));
    }
}
