/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_tb2;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Administradores = new javax.swing.JDialog();
        bt_CRUD_Software = new javax.swing.JButton();
        bt_CRUD_Desarollador = new javax.swing.JButton();
        bt_Salir_Admins = new javax.swing.JButton();
        jd_CRUD_Software = new javax.swing.JDialog();
        jtf_Codigo_Proyecto = new javax.swing.JTextField();
        jtf_Nombre_Proyecto = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jl_Codigo_Proyecto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jl_Fecha_Inicio = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jd_CRUD_Desarollador = new javax.swing.JDialog();
        bt_Crear_Desarollador = new javax.swing.JButton();
        bt_Cerrar_CRUD_Desarollador = new javax.swing.JButton();
        bt_Ver_Desarolladores = new javax.swing.JButton();
        jtf_Codigo_Desarollador = new javax.swing.JTextField();
        jtf_Lenguaje_Domina = new javax.swing.JTextField();
        jtf_Nombre_Empleado = new javax.swing.JTextField();
        jtf_Tecnologia_Domina = new javax.swing.JTextField();
        jl_Codigo_Desarollador = new javax.swing.JLabel();
        jl_Nombre_Desarollador = new javax.swing.JLabel();
        jl_Lengauaje_Domina = new javax.swing.JLabel();
        jl_Tecnologia_Domina = new javax.swing.JLabel();
        jd_Ver_Desarollador = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Desarolladores = new javax.swing.JTable();
        bt_Modificar_Desarollador = new javax.swing.JButton();
        bt_Cerrar_Ver_Desarrollador = new javax.swing.JButton();
        bt_Borrar_Desarollador = new javax.swing.JButton();
        jtf_Roll = new javax.swing.JTextField();
        bt_Login = new javax.swing.JButton();
        jpf_Contraseña = new javax.swing.JPasswordField();
        jl_Rol = new javax.swing.JLabel();
        jl_Contraseña = new javax.swing.JLabel();
        jl_Usuario = new javax.swing.JLabel();
        jtf_Usuario = new javax.swing.JTextField();

        bt_CRUD_Software.setText("CRUD Sofware");
        bt_CRUD_Software.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_CRUD_SoftwareMouseClicked(evt);
            }
        });

        bt_CRUD_Desarollador.setText("CRUD Desarollador");
        bt_CRUD_Desarollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_CRUD_DesarolladorMouseClicked(evt);
            }
        });

        bt_Salir_Admins.setText("Salir");
        bt_Salir_Admins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Salir_AdminsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_AdministradoresLayout = new javax.swing.GroupLayout(jd_Administradores.getContentPane());
        jd_Administradores.getContentPane().setLayout(jd_AdministradoresLayout);
        jd_AdministradoresLayout.setHorizontalGroup(
            jd_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AdministradoresLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(bt_CRUD_Software)
                .addGap(18, 18, 18)
                .addComponent(bt_CRUD_Desarollador)
                .addGap(18, 18, 18)
                .addComponent(bt_Salir_Admins)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_AdministradoresLayout.setVerticalGroup(
            jd_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AdministradoresLayout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addGroup(jd_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_CRUD_Software)
                    .addComponent(bt_CRUD_Desarollador)
                    .addComponent(bt_Salir_Admins))
                .addGap(43, 43, 43))
        );

        jTextField4.setText("jTextField1");

        jTextField10.setText("jTextField1");

        jTextField11.setText("jTextField1");

        jTextField12.setText("jTextField1");

        jTextField13.setText("jTextField1");

        jTextField14.setText("jTextField1");

        jl_Codigo_Proyecto.setText("Codigo del Proyecto");

        jLabel2.setText("Nombre del Proyecto");

        jLabel3.setText("jLabel1");

        jLabel4.setText("jLabel1");

        jLabel5.setText("jLabel1");

        jLabel6.setText("jLabel1");

        jLabel7.setText("jLabel1");

        jLabel8.setText("jLabel1");

        jLabel9.setText("jLabel1");

        jl_Fecha_Inicio.setText("Fecha de Inicio");

        jLabel11.setText("jLabel1");

        jLabel13.setText("jLabel1");

        jLabel15.setText("jLabel1");

        javax.swing.GroupLayout jd_CRUD_SoftwareLayout = new javax.swing.GroupLayout(jd_CRUD_Software.getContentPane());
        jd_CRUD_Software.getContentPane().setLayout(jd_CRUD_SoftwareLayout);
        jd_CRUD_SoftwareLayout.setHorizontalGroup(
            jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                                .addComponent(jl_Codigo_Proyecto)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_Codigo_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15))
                            .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))))
                    .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel9))
                    .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jl_Fecha_Inicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_Nombre_Proyecto)
                            .addComponent(jTextField3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                    .addContainerGap(198, Short.MAX_VALUE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(145, 145, 145)))
            .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                    .addContainerGap(208, Short.MAX_VALUE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(135, 135, 135)))
            .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                    .addContainerGap(218, Short.MAX_VALUE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(125, 125, 125)))
            .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                    .addContainerGap(228, Short.MAX_VALUE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(115, 115, 115)))
            .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                    .addContainerGap(238, Short.MAX_VALUE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(105, 105, 105)))
            .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                    .addGap(132, 132, 132)
                    .addComponent(jLabel13)
                    .addContainerGap(239, Short.MAX_VALUE)))
        );
        jd_CRUD_SoftwareLayout.setVerticalGroup(
            jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Codigo_Proyecto)
                    .addComponent(jtf_Codigo_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_Nombre_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_Fecha_Inicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
            .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                    .addContainerGap(156, Short.MAX_VALUE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(122, 122, 122)))
            .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                    .addContainerGap(166, Short.MAX_VALUE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(112, 112, 112)))
            .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                    .addContainerGap(176, Short.MAX_VALUE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(102, 102, 102)))
            .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                    .addContainerGap(186, Short.MAX_VALUE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(92, 92, 92)))
            .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CRUD_SoftwareLayout.createSequentialGroup()
                    .addContainerGap(196, Short.MAX_VALUE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(82, 82, 82)))
            .addGroup(jd_CRUD_SoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_CRUD_SoftwareLayout.createSequentialGroup()
                    .addGap(142, 142, 142)
                    .addComponent(jLabel13)
                    .addContainerGap(142, Short.MAX_VALUE)))
        );

        bt_Crear_Desarollador.setText("Crear");
        bt_Crear_Desarollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Crear_DesarolladorMouseClicked(evt);
            }
        });

        bt_Cerrar_CRUD_Desarollador.setText("Cerrar Ventana");
        bt_Cerrar_CRUD_Desarollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Cerrar_CRUD_DesarolladorMouseClicked(evt);
            }
        });

        bt_Ver_Desarolladores.setText("Ver Desarolladores");
        bt_Ver_Desarolladores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Ver_DesarolladoresMouseClicked(evt);
            }
        });

        jl_Codigo_Desarollador.setText("Codigo de Desarollador");

        jl_Nombre_Desarollador.setText("Nombre");

        jl_Lengauaje_Domina.setText("Lenguaje que domina");

        jl_Tecnologia_Domina.setText("Tecnologia que domina");

        javax.swing.GroupLayout jd_CRUD_DesarolladorLayout = new javax.swing.GroupLayout(jd_CRUD_Desarollador.getContentPane());
        jd_CRUD_Desarollador.getContentPane().setLayout(jd_CRUD_DesarolladorLayout);
        jd_CRUD_DesarolladorLayout.setHorizontalGroup(
            jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CRUD_DesarolladorLayout.createSequentialGroup()
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_CRUD_DesarolladorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl_Tecnologia_Domina)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_Tecnologia_Domina))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CRUD_DesarolladorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_Crear_Desarollador)
                            .addComponent(jl_Codigo_Desarollador)
                            .addComponent(jl_Nombre_Desarollador)
                            .addComponent(jl_Lengauaje_Domina))
                        .addGap(18, 18, 18)
                        .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_Codigo_Desarollador)
                            .addComponent(jtf_Nombre_Empleado)
                            .addGroup(jd_CRUD_DesarolladorLayout.createSequentialGroup()
                                .addComponent(bt_Ver_Desarolladores)
                                .addGap(18, 18, 18)
                                .addComponent(bt_Cerrar_CRUD_Desarollador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                            .addComponent(jtf_Lenguaje_Domina))))
                .addGap(100, 100, 100))
        );
        jd_CRUD_DesarolladorLayout.setVerticalGroup(
            jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CRUD_DesarolladorLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Codigo_Desarollador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Codigo_Desarollador))
                .addGap(18, 18, 18)
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre_Desarollador)
                    .addComponent(jtf_Nombre_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Lengauaje_Domina)
                    .addComponent(jtf_Lenguaje_Domina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Tecnologia_Domina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Tecnologia_Domina))
                .addGap(75, 75, 75)
                .addGroup(jd_CRUD_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Crear_Desarollador)
                    .addComponent(bt_Ver_Desarolladores)
                    .addComponent(bt_Cerrar_CRUD_Desarollador))
                .addGap(22, 22, 22))
        );

        jt_Desarolladores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Codigo", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_Desarolladores);
        if (jt_Desarolladores.getColumnModel().getColumnCount() > 0) {
            jt_Desarolladores.getColumnModel().getColumn(0).setResizable(false);
            jt_Desarolladores.getColumnModel().getColumn(1).setResizable(false);
        }

        bt_Modificar_Desarollador.setText("Modificar");
        bt_Modificar_Desarollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Modificar_DesarolladorMouseClicked(evt);
            }
        });

        bt_Cerrar_Ver_Desarrollador.setText("Cerrar Ventana");
        bt_Cerrar_Ver_Desarrollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Cerrar_Ver_DesarrolladorMouseClicked(evt);
            }
        });

        bt_Borrar_Desarollador.setText("Borrar");
        bt_Borrar_Desarollador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Borrar_DesarolladorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_Ver_DesarolladorLayout = new javax.swing.GroupLayout(jd_Ver_Desarollador.getContentPane());
        jd_Ver_Desarollador.getContentPane().setLayout(jd_Ver_DesarolladorLayout);
        jd_Ver_DesarolladorLayout.setHorizontalGroup(
            jd_Ver_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Ver_DesarolladorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jd_Ver_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_Borrar_Desarollador)
                    .addComponent(bt_Modificar_Desarollador)
                    .addComponent(bt_Cerrar_Ver_Desarrollador))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jd_Ver_DesarolladorLayout.setVerticalGroup(
            jd_Ver_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Ver_DesarolladorLayout.createSequentialGroup()
                .addGroup(jd_Ver_DesarolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_Ver_DesarolladorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_Ver_DesarolladorLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(bt_Modificar_Desarollador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Borrar_Desarollador)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Cerrar_Ver_Desarrollador)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_Login.setText("Login");
        bt_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_LoginMouseClicked(evt);
            }
        });

        jl_Rol.setText("Ingrese su rol");

        jl_Contraseña.setText("Ingrese su contraseña");

        jl_Usuario.setText("Ingrese su usario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Contraseña)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Usuario)
                            .addComponent(jl_Rol))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(bt_Login)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jtf_Roll)
                    .addComponent(jpf_Contraseña, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_Usuario))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_Roll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Rol))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Usuario)
                    .addComponent(jtf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpf_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Contraseña))
                .addGap(18, 18, 18)
                .addComponent(bt_Login)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_LoginMouseClicked
        // TODO add your handling code here:
        String rol;
        String clave;
        String usuario;
        rol = jtf_Roll.getText();
        clave = jpf_Contraseña.getText();
        usuario = jtf_Usuario.getText();
        for (int i = 0; i < users.size(); i++) {
            if (usuario.equalsIgnoreCase(users.get(i).getCredenciales()) && clave.equals(users.get(i).getClave()) && rol.equalsIgnoreCase("administrador")) {
                jtf_Roll.setText("");
                jpf_Contraseña.setText("");
                jtf_Usuario.setText("");
                jd_Administradores.setLocationRelativeTo(this);
                jd_Administradores.setVisible(true);
                jd_Administradores.setSize(250, 250);

            } else if (usuario.equalsIgnoreCase(users.get(i).getCredenciales()) && clave.equals(users.get(i).getClave()) && rol.equalsIgnoreCase("desarollador")) {
                jtf_Roll.setText("");
                jpf_Contraseña.setText("");
                jtf_Usuario.setText("");
                System.out.println("desarollador");
            } else if (usuario.equalsIgnoreCase(users.get(i).getCredenciales()) && clave.equals(users.get(i).getClave()) && rol.equalsIgnoreCase("qa")) {
                jtf_Roll.setText("");
                jpf_Contraseña.setText("");
                jtf_Usuario.setText("");
                System.out.println("qa");
            }
        }//Fim del for que hace las validaciones del usuario
    }//GEN-LAST:event_bt_LoginMouseClicked

    private void bt_CRUD_SoftwareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CRUD_SoftwareMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_bt_CRUD_SoftwareMouseClicked

    private void bt_Cerrar_CRUD_DesarolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Cerrar_CRUD_DesarolladorMouseClicked
        // TODO add your handling code here:
        jd_CRUD_Desarollador.setVisible(false);
    }//GEN-LAST:event_bt_Cerrar_CRUD_DesarolladorMouseClicked

    private void bt_Crear_DesarolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Crear_DesarolladorMouseClicked
        // TODO add your handling code here:
        Desarollador de = new Desarollador(Integer.parseInt(jtf_Codigo_Desarollador.getText()), jtf_Nombre_Empleado.getText());
        de.addLenguaje(jtf_Lenguaje_Domina.getText());
        de.addTecnologia(jtf_Tecnologia_Domina.getText());
        users.add(new Usuarios(jtf_Codigo_Desarollador.getText(), "123"));
        desarolladores.add(de);
        jtf_Codigo_Desarollador.setText("");
        jtf_Nombre_Empleado.setText("");
        jtf_Lenguaje_Domina.setText("");
        jtf_Tecnologia_Domina.setText("");
    }//GEN-LAST:event_bt_Crear_DesarolladorMouseClicked

    private void bt_CRUD_DesarolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CRUD_DesarolladorMouseClicked
        // TODO add your handling code here:
        jd_CRUD_Desarollador.setLocationRelativeTo(this);
        jd_CRUD_Desarollador.setVisible(true);
        jd_CRUD_Desarollador.setSize(250, 250);
    }//GEN-LAST:event_bt_CRUD_DesarolladorMouseClicked

    private void bt_Salir_AdminsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Salir_AdminsMouseClicked
        // TODO add your handling code here:
        jd_Administradores.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_bt_Salir_AdminsMouseClicked

    private void bt_Ver_DesarolladoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Ver_DesarolladoresMouseClicked
        // TODO add your handling code here:
        jd_Ver_Desarollador.setLocationRelativeTo(this);
        jd_Ver_Desarollador.setVisible(true);
        jd_Ver_Desarollador.setSize(250, 250);

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Codigo");
        model.addColumn("Nombre");
        for (int i = 0; i < desarolladores.size(); i++) {
            model.addRow(new Object[]{"" + desarolladores.get(i).getCodigo_D(), "" + desarolladores.get(i).getNombre()});
        }
        jt_Desarolladores.setModel(model);
    }//GEN-LAST:event_bt_Ver_DesarolladoresMouseClicked

    private void bt_Cerrar_Ver_DesarrolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Cerrar_Ver_DesarrolladorMouseClicked
        // TODO add your handling code here:
        jd_Ver_Desarollador.setVisible(false);
    }//GEN-LAST:event_bt_Cerrar_Ver_DesarrolladorMouseClicked

    private void bt_Borrar_DesarolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Borrar_DesarolladorMouseClicked
        // TODO add your handling code here:
        desarolladores.remove(jt_Desarolladores.getSelectedRow());
        DefaultTableModel model = (DefaultTableModel) jt_Desarolladores.getModel();
        model.removeRow(jt_Desarolladores.getSelectedRow());
        jt_Desarolladores.setModel(model);
    }//GEN-LAST:event_bt_Borrar_DesarolladorMouseClicked

    private void bt_Modificar_DesarolladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Modificar_DesarolladorMouseClicked
        // TODO add your handling code here:
        String input;
        input = JOptionPane.showInputDialog(jd_CRUD_Desarollador, "1. Asignar Bug\n2. Agregar Tecnologia\n3. Agregar Lenguaje\n4. Modificar Codigo\n Ingrese una opcion: ");
        switch (input) {
            case "1": {
                String desa;
                String asignar;
                desa = JOptionPane.showInputDialog(jd_CRUD_Desarollador, "Ingrese el codigo del desarollador a asignar el bug: ");
                String bug = "";
                for (int i = 0; i < bugs.size(); i++) {
                    bug += "" + bugs.get(i).getCodigo() + "\n";
                }
                asignar = JOptionPane.showInputDialog(jd_CRUD_Desarollador, bug + "\nIngrese un bug a asignar");

                for (int i = 0; i < desarolladores.size(); i++) {
                    if (desarolladores.get(i).getCodigo_D() == Integer.parseInt(desa)) {
                        desarolladores.get(i).setReparar(bugs.get(Integer.parseInt(asignar)));
                    }
                }

                break;
            }
            case "2": {
                String desa;
                String asignar;
                desa = JOptionPane.showInputDialog(jd_CRUD_Desarollador, "Ingrese el codigo del desarollador a agregar la tecnologia: ");

                asignar = JOptionPane.showInputDialog(jd_CRUD_Desarollador, "Ingrese la tecnologia a agregar: ");

                for (int i = 0; i < desarolladores.size(); i++) {
                    if (desarolladores.get(i).getCodigo_D() == Integer.parseInt(desa)) {
                        desarolladores.get(i).addTecnologia(asignar);
                    }
                }
                break;
            }
            case "3": {
                String desa;
                String asignar;
                desa = JOptionPane.showInputDialog(jd_CRUD_Desarollador, "Ingrese el codigo del desarollador a agregar ellenguaje: ");

                asignar = JOptionPane.showInputDialog(jd_CRUD_Desarollador, "Ingrese el lenguaje a agregar: ");

                for (int i = 0; i < desarolladores.size(); i++) {
                    if (desarolladores.get(i).getCodigo_D() == Integer.parseInt(desa)) {
                        desarolladores.get(i).addLenguaje(asignar);
                    }
                }
            }
            break;
            case "4":{
                 String desa;
                String asignar;
                desa = JOptionPane.showInputDialog(jd_CRUD_Desarollador, "Ingrese el codigo del desarollador a agregar ellenguaje: ");

                asignar = JOptionPane.showInputDialog(jd_CRUD_Desarollador, "Ingrese el nuevo codigo: ");

                for (int i = 0; i < desarolladores.size(); i++) {
                    if (desarolladores.get(i).getCodigo_D() == Integer.parseInt(desa)) {
                        desarolladores.get(i).setCodigo_D(Integer.parseInt(asignar));
                    }
                }
            
                break;}

            default:
                JOptionPane.showMessageDialog(jd_CRUD_Desarollador, "Opcion no valida");

        }//casos para las opciones para modificar el desarollador
    }//GEN-LAST:event_bt_Modificar_DesarolladorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        agregar_pre();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Borrar_Desarollador;
    private javax.swing.JButton bt_CRUD_Desarollador;
    private javax.swing.JButton bt_CRUD_Software;
    private javax.swing.JButton bt_Cerrar_CRUD_Desarollador;
    private javax.swing.JButton bt_Cerrar_Ver_Desarrollador;
    private javax.swing.JButton bt_Crear_Desarollador;
    private javax.swing.JButton bt_Login;
    private javax.swing.JButton bt_Modificar_Desarollador;
    private javax.swing.JButton bt_Salir_Admins;
    private javax.swing.JButton bt_Ver_Desarolladores;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JDialog jd_Administradores;
    private javax.swing.JDialog jd_CRUD_Desarollador;
    private javax.swing.JDialog jd_CRUD_Software;
    private javax.swing.JDialog jd_Ver_Desarollador;
    private javax.swing.JLabel jl_Codigo_Desarollador;
    private javax.swing.JLabel jl_Codigo_Proyecto;
    private javax.swing.JLabel jl_Contraseña;
    private javax.swing.JLabel jl_Fecha_Inicio;
    private javax.swing.JLabel jl_Lengauaje_Domina;
    private javax.swing.JLabel jl_Nombre_Desarollador;
    private javax.swing.JLabel jl_Rol;
    private javax.swing.JLabel jl_Tecnologia_Domina;
    private javax.swing.JLabel jl_Usuario;
    private javax.swing.JPasswordField jpf_Contraseña;
    private javax.swing.JTable jt_Desarolladores;
    private javax.swing.JTextField jtf_Codigo_Desarollador;
    private javax.swing.JTextField jtf_Codigo_Proyecto;
    private javax.swing.JTextField jtf_Lenguaje_Domina;
    private javax.swing.JTextField jtf_Nombre_Empleado;
    private javax.swing.JTextField jtf_Nombre_Proyecto;
    private javax.swing.JTextField jtf_Roll;
    private javax.swing.JTextField jtf_Tecnologia_Domina;
    private javax.swing.JTextField jtf_Usuario;
    // End of variables declaration//GEN-END:variables
    static ArrayList<Usuarios> users = new ArrayList();
    static ArrayList<Desarollador> desarolladores = new ArrayList();
    static ArrayList<Bug> bugs = new ArrayList();

    public static void agregar_pre() {
        users.add(new Usuarios("administrador", "123"));
        users.add(new Usuarios("desarollador", "456"));
        users.add(new Usuarios("qa", "789"));
    }
}
